name: Run with URL

on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL to process"
        required: true
        type: string

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Processing ${{ github.event.inputs.url }} on branch ${{ github.ref }}"
